- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Transfer the script
  copy: src=scripts/nginx_repo.sh dest=/home mode=0777

- name: Execute the script
  command: bash /home/nginx_repo.sh

- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600
      
- name: "install nginx"
  apt:
    name: ['nginx']
    state: latest

- name: "create project directory"
  file:
    path: /usr/share/nginx/html/{{ project }}
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  
- name: copy index file
  copy: 
    src: files/index.php
    dest: /usr/share/nginx/html/{{ project }}
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


- name: delete default nginx site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
    #    notify: restart nginx

    # handlers:
    #- name: "restart nginx"
    #  service:
    #    name: nginx
    #    state: restarted

- name: copy fastcgi.conf to nginx directory
  template:
    src: templates/fastcgi.conf.j2
    dest: /etc/nginx/fastcgi.conf
    owner: root
    group: root
    mode: '0644'
    #  notify: restart nginx

- name: copy fastcgi-php.conf to nginx directory
  template:
    src: templates/fastcgi-php.conf.j2
    dest: /etc/nginx/fastcgi-php.conf
    owner: root
    group: root
    mode: '0644'
    #  notify: restart nginx


- name: "create snippets inside nginx directory"
  file:
    path: /etc/nginx/snippets
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy fastcgi-php.conf to nginx directory
  template:
    src: templates/fastcgi-php.conf.j2
    dest: /etc/nginx/snippets/fastcgi-php.conf
    owner: root
    group: root
    mode: '0644'
    #  notify: restart nginx

    
- name: copy nginx configuration file to conf.d
  template:
    src: templates/site.conf.j2
    dest: /etc/nginx/conf.d/{{ domain }}.conf
    owner: root
    group: root
    mode: '0644'
    #  notify: restart nginx


    # handlers:
- name: "restart nginx"
  service:
    name: nginx
    state: restarted




